# Generated by Django 5.0.1 on 2024-02-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_img',
        ),
    ]
