# Generated by Django 5.0.1 on 2024-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='thumbnail',
            field=models.FileField(default=True, upload_to='static/img/'),
        ),
    ]
